name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "11", "17"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --file pom.xml package
    - name: Check Javadocs
      run: mvn --batch-mode --file pom.xml --activate-profiles release org.apache.maven.plugins:maven-javadoc-plugin:jar
